### ISSUE TITLE
The result of this line is not good

### ISSUE THREAD

**Issue by DocteurNo** [scls19fr/word_gen#3]
https://github.com/scls19fr/word_gen/blob/fceaaab0bbb6dd984ef769d0feec467500091d60/mots_2D_2.py#L36

Sorry for my bad english

**Comment by s-celles** [comment]
```
mots_2D_2.py:36: RuntimeWarning: invalid value encountered in true_divide
  p = count.astype('float') / st
```

that's just a warning... not an error
